parameters:

    # When I refer to a sandbox install I refer to our sandbox and sites
    # that are on a proper remote server in a domain root (e.g. David's Site).
    # Local sites are sites on your computer/local network that probably don't have things

    # Shouldn't need to touch this
    database_driver:        pdo_mysql
    phpbb_database_driver:  pdo_mysql
    database_host:          localhost
    phpbb_database_host:    localhost
    database_port:          ~
    phpbb_database_port:    ~

    # Its not rocket science, the user should have access to make dbs and have full access to it (we create it later)
    # This is the DB for Symfony
    database_name:      www_tests_symfony
    database_user:      root
    database_password:  ~

    # phpBB database
    phpbb_database_name:        www_tests_phpbb
    phpbb_database_user:        root
    phpbb_database_password:    ~

    # Databases for testing
    test_database_driver:            pdo_mysql
    phpbb_test_database_driver:      pdo_mysql
    test_database_host:              localhost
    phpbb_test_database_host:        localhost
    test_database_port:              ~
    phpbb_test_database_port:        ~
    test_database_name:              www_tests_symfony
    test_database_user:              root
    test_database_password:          ~
    phpbb_test_database_name:        www_tests_phpbb
    phpbb_test_database_user:        root
    phpbb_test_database_password:    ~

    # Mailer Settings, shouldn't need to touch these unless its a live/sandbox install.
    mailer_transport:   smtp
    mailer_host:        localhost
    mailer_user:        ~
    mailer_password:    ~

    locale:             en
    secret:             TravisRandomToken

    # Location should be local, sandbox or live
    location:           local

    # Location of java on this computer/server
    java_location:      /usr/bin/java
