parameters:

    # When I refer to a sandbox install I refer to our sandbox and sites
    # that are on a proper remote server in a domain root (e.g. David's Site).
    # Local sites are sites on your computer/local network that probably don't have things

    # Shouldn't need to touch this
    database_driver:        pdo_mysql
    phpbb_database_driver:  pdo_mysql
    database_host:          localhost
    phpbb_database_host:    localhost
    database_port:          ~
    phpbb_database_port:    ~

    # Its not rocket science, the user should have access to make dbs and have full access to it (we create it later)
    # This is the DB for Symfony
    database_name:      www_tests_symfony
    database_user:      bamboo_test_user
    database_password:  hlgiHu7hFD

    # phpBB database
    phpbb_database_name:        www_tests_phpbb
    phpbb_database_user:        bamboo_test_user
    phpbb_database_password:    hlgiHu7hFD
    phpbb_database_prefix:      community_

    # Databases for testing
    test_database_driver:            pdo_mysql
    phpbb_test_database_driver:      pdo_mysql
    test_database_host:              localhost
    phpbb_test_database_host:        localhost
    test_database_port:              ~
    phpbb_test_database_port:        ~
    test_database_name:              www_tests_symfony
    test_database_user:              bamboo_test_user
    test_database_password:          hlgiHu7hFD
    phpbb_test_database_name:        www_tests_phpbb
    phpbb_test_database_user:        bamboo_test_user
    phpbb_test_database_password:    hlgiHu7hFD

    # Mailer Settings, shouldn't need to touch these unless its a live/sandbox install.
    mailer_transport:   mail
    mailer_host:        ~
    mailer_user:        ~
    mailer_password:    ~
    mailer_port:        ~
    mailer_encryption:  ~
    mailer_auth_mode:   ~
    mailer_delivery_address:   ~
    mailer_disable_delivery:   true

    locale:             en
    secret:             ThisTokenIsNotSoSecretChangeIt

    # phpbb.memcached_cache for memcache, phpbb.apc_cache for file cache
    cacheDriver:        phpbb.apc_cache
    # memcached or array
    ormCache:           array
    # localhost or ~
    ormCacheHost: ~
    # 11211 or ~
    ormCachePort: ~
    # Memcached or ~
    ormCacheInstanceClass: ~

    # Location should be local, sandbox or live
    location:           local

    # Location of java on this computer/server
    java_location:      /usr/bin/java
