phpBBWebsite_Development_home:
    path:  /
    defaults:
        _controller:  PhpbbWebsiteInterfaceBundle:Global:template
        template: PhpbbWebsiteInterfaceBundle:Development:home.html.twig
    methods:  [GET]

phpBBWebsite_Development_prosilver:
    path: /prosilver/
    defaults: { _controller: PhpbbWebsiteInterfaceBundle:Development:prosilver, page: 1 }
    methods:  [GET]

phpBBWebsite_Development_prosilver_page:
    path: /prosilver/{page}
    defaults: { _controller: PhpbbWebsiteInterfaceBundle:Development:prosilver, page: 1 }
    methods:  [GET]
    requirements:
        page:  \d+

phpBBWebsite_Development_getInvolved:
    path:  /get-involved/
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /get-involved/
        permanent: true
