phpBBWebsite_Development_home:
    path:  /
    defaults:
        _controller: AppBundle:StaticTemplate:staticTemplate
        template: AppBundle:Development:home.html.twig
    methods:  [GET]

phpBBWebsite_Development_gsoc:
    path:  /gsoc/
    defaults:
        _controller: AppBundle:StaticTemplate:staticTemplate
        template: AppBundle:Development:gsoc.html.twig
    methods:  [GET]

phpBBWebsite_Development_gsoc_ideas:
    path:  /gsoc/ideas/
    defaults:
        _controller: AppBundle:StaticTemplate:staticTemplate
        template: AppBundle:Development:gsoc_ideas.html.twig
    methods:  [GET]

phpBBWebsite_Development_prosilver:
    path: /prosilver/
    defaults: { _controller: AppBundle:Development:prosilver, page: 1 }
    methods:  [GET]

phpBBWebsite_Development_prosilver_page:
    path: /prosilver/{page}
    defaults: { _controller: AppBundle:Development:prosilver, page: 1 }
    methods:  [GET]
    requirements:
        page:  \d+

phpBBWebsite_Development_getInvolved:
    path:  /get-involved/
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /get-involved/
        permanent: true
