phpBBWebsite_Styles_home:
    path:  /
    defaults:
        _controller: AppBundle:StaticTemplate:staticTemplate
        template: AppBundle:Styles:home.html.twig
    methods:  [GET]

phpBBWebsite_Styles_support:
    path:  /support/
    defaults:
        _controller: AppBundle:StaticTemplate:staticTemplate
        template: AppBundle:Styles:support.html.twig
    methods:  [GET]

phpBBWebsite_Styles_installing:
    path:  /installing/
    defaults:
        _controller: AppBundle:StaticTemplate:staticTemplate
        template: AppBundle:Styles:installing.html.twig
    methods:  [GET]

phpBBWebsite_Styles_create:
    path:  /create/
    defaults:
        _controller: AppBundle:StaticTemplate:staticTemplate
        template: AppBundle:Styles:create.html.twig
    methods:  [GET]

phpBBWebsite_Styles_team_overview:
    path:  /team-overview/
    defaults:
        _controller: AppBundle:StaticTemplate:staticTemplate
        template: AppBundle:Styles:team-overview.html.twig
    methods:  [GET]

phpBBWebsite_Styles_junior_validators:
    path:  /junior-validators/
    defaults:
        _controller: AppBundle:StaticTemplate:staticTemplate
        template: AppBundle:Styles:junior-validators.html.twig
    methods:  [GET]

phpBBWebsite_Styles_demo:
    path:  /demo/
    defaults:
        _controller: AppBundle:StaticTemplate:staticTemplate
        template: AppBundle:Styles:demo.html.twig
    methods:  [GET]

phpBBWebsite_Styles_demo_not_ready:
    path:  /demo/3.1/
    defaults:
        _controller: AppBundle:StaticTemplate:staticTemplate
        template: AppBundle:Styles:demoNotReady.html.twig
    methods:  [GET]

phpBBWebsite_Styles_rules_and_policies:
    path:  /rules-and-policies/
    defaults:
        _controller: AppBundle:StaticTemplate:staticTemplate
        template: AppBundle:Styles:rules-policies.html.twig
    methods:  [GET]

phpBBWebsite_Styles_dev_forum_rules:
    path:  /rules-and-policies/development-rules/
    defaults:
        _controller: AppBundle:StaticTemplate:staticTemplate
        template: AppBundle:Styles:dev-forum-rules.html.twig
    methods:  [GET]

phpBBWebsite_Styles_submission_policy_31x:
    path:  /rules-and-policies/submission-policy/3.1/
    defaults:
        _controller: AppBundle:StaticTemplate:staticTemplate
        template: AppBundle:Styles:submission-policy-31x.html.twig
    methods:  [GET]

phpBBWebsite_Styles_submission_policy_30x:
    path:  /rules-and-policies/submission-policy/3.0/
    defaults:
        _controller: AppBundle:StaticTemplate:staticTemplate
        template: AppBundle:Styles:submission-policy-30x.html.twig
    methods:  [GET]

phpBBWebsite_Styles_ssp_31x_redirect:
    path:  /ssp/
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /styles/rules-and-policies/submission-policy/3.1/
        permanent: true

phpBBWebsite_Styles_ssp_30x_redirect:
    path:  /ssp/3.0/
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /styles/rules-and-policies/submission-policy/3.0/
        permanent: true
