PhpbbWebsiteInterfaceBundle_homepage:
    path:  /
    defaults: { _controller: PhpbbWebsiteInterfaceBundle:Global:home }

phpBBWebsite_getInvolved:
    path:  /get-involved/
    defaults: { _controller: PhpbbWebsiteInterfaceBundle:About:getInvolved }
    methods:  [GET]

phpBBWebsite_demo:
    path:  /demo/
    defaults: { _controller: PhpbbWebsiteInterfaceBundle:Global:demo }
    methods:  [GET]

phpBBWebsite_customise:
    path:  /customise/
    defaults: { _controller: PhpbbWebsiteInterfaceBundle:Global:customise }
    methods:  [GET]

phpBBWebsite_About_contact_redirect:
    path:  /contact/
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /about/contact/
        permanent: true

phpBBWebsite_About:
    resource: "@PhpbbWebsiteInterfaceBundle/Resources/config/routing/about.yml"
    prefix:   /about

phpBBWebsite_Mods:
    resource: "@PhpbbWebsiteInterfaceBundle/Resources/config/routing/mods.yml"
    prefix:   /mods

phpBBWebsite_Development:
    resource: "@PhpbbWebsiteInterfaceBundle/Resources/config/routing/development.yml"
    prefix:   /development

phpBBWebsite_Support:
    resource: "@PhpbbWebsiteInterfaceBundle/Resources/config/routing/support.yml"
    prefix:   /support

phpBBWebsite_Extensions:
    resource: "@PhpbbWebsiteInterfaceBundle/Resources/config/routing/extensions.yml"
    prefix:   /extensions

phpBBWebsite_Downloads:
    resource: "@PhpbbWebsiteInterfaceBundle/Resources/config/routing/downloads.yml"
    prefix:   /downloads
